const COUNTRY_ALIASES = new Map(
  [
    ["angola", "AO"],
    ["benin", "BJ"],
    ["botswana", "BW"],
    ["burkina faso", "BF"],
    ["burundi", "BI"],
    ["cabo verde", "CV"],
    ["cape verde", "CV"],
    ["cameroon", "CM"],
    ["central african republic", "CF"],
    ["chad", "TD"],
    ["comoros", "KM"],
    ["congo", "CG"],
    ["republic of the congo", "CG"],
    ["democratic republic of the congo", "CD"],
    ["drc", "CD"],
    ["djibouti", "DJ"],
    ["egypt", "EG"],
    ["equatorial guinea", "GQ"],
    ["eritrea", "ER"],
    ["eswatini", "SZ"],
    ["swaziland", "SZ"],
    ["ethiopia", "ET"],
    ["gabon", "GA"],
    ["gambia", "GM"],
    ["the gambia", "GM"],
    ["ghana", "GH"],
    ["guinea", "GN"],
    ["guinea bissau", "GW"],
    ["ivory coast", "CI"],
    ["cote d ivoire", "CI"],
    ["kenya", "KE"],
    ["lesotho", "LS"],
    ["liberia", "LR"],
    ["libya", "LY"],
    ["madagascar", "MG"],
    ["malawi", "MW"],
    ["mali", "ML"],
    ["mauritania", "MR"],
    ["mauritius", "MU"],
    ["morocco", "MA"],
    ["mozambique", "MZ"],
    ["namibia", "NA"],
    ["niger", "NE"],
    ["nigeria", "NG"],
    ["rwanda", "RW"],
    ["sao tome and principe", "ST"],
    ["senegal", "SN"],
    ["seychelles", "SC"],
    ["sierra leone", "SL"],
    ["somalia", "SO"],
    ["south africa", "ZA"],
    ["south sudan", "SS"],
    ["sudan", "SD"],
    ["tanzania", "TZ"],
    ["togo", "TG"],
    ["tunisia", "TN"],
    ["uganda", "UG"],
    ["zambia", "ZM"],
    ["zimbabwe", "ZW"],
    ["afghanistan", "AF"],
    ["albania", "AL"],
    ["algeria", "DZ"],
    ["argentina", "AR"],
    ["armenia", "AM"],
    ["australia", "AU"],
    ["austria", "AT"],
    ["azerbaijan", "AZ"],
    ["bahamas", "BS"],
    ["bahrain", "BH"],
    ["bangladesh", "BD"],
    ["barbados", "BB"],
    ["belarus", "BY"],
    ["belgium", "BE"],
    ["belize", "BZ"],
    ["bhutan", "BT"],
    ["bolivia", "BO"],
    ["bosnia", "BA"],
    ["bosnia and herzegovina", "BA"],
    ["brazil", "BR"],
    ["brunei", "BN"],
    ["bulgaria", "BG"],
    ["cambodia", "KH"],
    ["canada", "CA"],
    ["chile", "CL"],
    ["china", "CN"],
    ["colombia", "CO"],
    ["costa rica", "CR"],
    ["croatia", "HR"],
    ["cuba", "CU"],
    ["cyprus", "CY"],
    ["czech republic", "CZ"],
    ["czechia", "CZ"],
    ["denmark", "DK"],
    ["dominican republic", "DO"],
    ["ecuador", "EC"],
    ["el salvador", "SV"],
    ["estonia", "EE"],
    ["finland", "FI"],
    ["france", "FR"],
    ["georgia", "GE"],
    ["germany", "DE"],
    ["greece", "GR"],
    ["guatemala", "GT"],
    ["haiti", "HT"],
    ["honduras", "HN"],
    ["hungary", "HU"],
    ["iceland", "IS"],
    ["india", "IN"],
    ["indonesia", "ID"],
    ["iran", "IR"],
    ["iraq", "IQ"],
    ["ireland", "IE"],
    ["israel", "IL"],
    ["italy", "IT"],
    ["jamaica", "JM"],
    ["japan", "JP"],
    ["jordan", "JO"],
    ["kazakhstan", "KZ"],
    ["kuwait", "KW"],
    ["kyrgyzstan", "KG"],
    ["laos", "LA"],
    ["latvia", "LV"],
    ["lebanon", "LB"],
    ["lithuania", "LT"],
    ["luxembourg", "LU"],
    ["malaysia", "MY"],
    ["maldives", "MV"],
    ["malta", "MT"],
    ["mexico", "MX"],
    ["moldova", "MD"],
    ["mongolia", "MN"],
    ["montenegro", "ME"],
    ["myanmar", "MM"],
    ["nepal", "NP"],
    ["netherlands", "NL"],
    ["new zealand", "NZ"],
    ["nicaragua", "NI"],
    ["north korea", "KP"],
    ["north macedonia", "MK"],
    ["norway", "NO"],
    ["oman", "OM"],
    ["pakistan", "PK"],
    ["panama", "PA"],
    ["paraguay", "PY"],
    ["peru", "PE"],
    ["philippines", "PH"],
    ["poland", "PL"],
    ["portugal", "PT"],
    ["qatar", "QA"],
    ["romania", "RO"],
    ["russia", "RU"],
    ["saudi arabia", "SA"],
    ["serbia", "RS"],
    ["singapore", "SG"],
    ["slovakia", "SK"],
    ["slovenia", "SI"],
    ["south korea", "KR"],
    ["spain", "ES"],
    ["sri lanka", "LK"],
    ["sweden", "SE"],
    ["switzerland", "CH"],
    ["syria", "SY"],
    ["taiwan", "TW"],
    ["tajikistan", "TJ"],
    ["thailand", "TH"],
    ["trinidad and tobago", "TT"],
    ["turkey", "TR"],
    ["turkiye", "TR"],
    ["turkmenistan", "TM"],
    ["ukraine", "UA"],
    ["united arab emirates", "AE"],
    ["uae", "AE"],
    ["united kingdom", "GB"],
    ["uk", "GB"],
    ["great britain", "GB"],
    ["england", "GB"],
    ["united states", "US"],
    ["united states of america", "US"],
    ["usa", "US"],
    ["us", "US"],
    ["america", "US"],
    ["uruguay", "UY"],
    ["uzbekistan", "UZ"],
    ["venezuela", "VE"],
    ["vietnam", "VN"],
    ["yemen", "YE"]
  ].sort((left, right) => right[0].length - left[0].length)
);

function findCountryIdInText(text) {
  const normalized = text.replace(/[^a-z0-9]+/g, " ").replace(/\s+/g, " ").trim();
  const codeMatch = normalized.match(/\b(?:from|in)\s+([a-z]{2})\b/);

  if (codeMatch) {
    return codeMatch[1].toUpperCase();
  }

  for (const [name, countryId] of COUNTRY_ALIASES.entries()) {
    const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const pattern = new RegExp(`(?:^|\\s)${escaped}(?:\\s|$)`, "i");

    if (pattern.test(normalized)) {
      return countryId;
    }
  }

  return undefined;
}

module.exports = {
  findCountryIdInText
};
